### ISSUE TITLE
Could not pass event EntityDamageEvent

### ISSUE THREAD

**Issue by Naantam** [animeavi/FactionsGuard#1]
## System Information
Spigot MC 1.14.4
FactionsGuard v1.5
Factions v3.2.2
MassiveCore v3.2.2

## Error
[01:16:16] [Server thread/ERROR]: Could not pass event EntityDamageEvent to FactionsGuard v1.5
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:221) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:893) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:879) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:925) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
	at net.minecraft.server.v1_14_R1.EntityLiving.damageEntity0(EntityLiving.java:1620) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
	at net.minecraft.server.v1_14_R1.EntityLiving.damageEntity(EntityLiving.java:1073) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
	at net.minecraft.server.v1_14_R1.EntityBat.damageEntity(EntityBat.java:185) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
	at net.minecraft.server.v1_14_R1.Entity.burn(Entity.java:1059) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
	at net.minecraft.server.v1_14_R1.Entity.move(Entity.java:652) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
	at net.minecraft.server.v1_14_R1.EntityLiving.e(EntityLiving.java:2140) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
	at net.minecraft.server.v1_14_R1.EntityLiving.movementTick(EntityLiving.java:2486) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
	at net.minecraft.server.v1_14_R1.EntityInsentient.movementTick(EntityInsentient.java:502) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
	at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2293) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
	at net.minecraft.server.v1_14_R1.EntityInsentient.tick(EntityInsentient.java:273) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
	at net.minecraft.server.v1_14_R1.EntityBat.tick(EntityBat.java:86) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
	at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:568) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
	at net.minecraft.server.v1_14_R1.World.a(World.java:745) [spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:344) [spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1068) [spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:970) [spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:815) [spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.NoClassDefFoundError: com/massivecraft/factions/FLocation
	at io.github.animeavi.factionsguard.events.CommonEvent.getFaction(CommonEvent.java:31) ~[?:?]
	at io.github.animeavi.factionsguard.events.AnimalDamageEvent.onEntityDamage(AnimalDamageEvent.java:80) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
	... 26 more
Caused by: java.lang.ClassNotFoundException: com.massivecraft.factions.FLocation
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_221]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:135) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
	at io.github.animeavi.factionsguard.events.CommonEvent.getFaction(CommonEvent.java:31) ~[?:?]
	at io.github.animeavi.factionsguard.events.AnimalDamageEvent.onEntityDamage(AnimalDamageEvent.java:80) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
	... 26 more

**Comment by animeavi** [comment]
Only FactionsUUID is supported.
